version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '06:00'
      timezone: Asia/Tokyo
    open-pull-requests-limit: 25
    assignees:
      - nandenjin
    labels:
      - dependencies
    versioning-strategy: increase
